### ISSUE TITLE
<CR> in insert mode does nothing

### ISSUE THREAD

**Issue by nagy135** [m4xshen/autoclose.nvim#11]
Hi, not sure what context should i provide but for some reason after installing this plugin <CR> in insert mode does nothing. I disabled all of my plugins to test if something clashes but still the same. Any ideas?
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by nagy135** [comment]
after reading your code, there is no way its fault of this plugin ...will investigate elsewhere

**Comment by ripytide** [comment]
I also have just had this exact problem, deleting lines: https://github.com/m4xshen/autoclose.nvim/blob/ec7bf9013584e92e0a07b190c936b2c4563e961a/lua/autoclose.lua#L18-L19 fixed this for me though, perhaps it's remapping \<CR>?

**Comment by gilbh** [comment]
Had a similar conflict with Coc, when `<CR>` would not work because of this remapping. 

Any change of making the following lines disabled as an option in the configuration?
```
      ["<BS>"] = {},
      ["<C-H>"] = {},
      ["<C-W>"] = {},
      ["<CR>"] = {},
      ["<S-CR>"] = {},
 ```

**Comment by m4xshen** [comment]
> I also have just had this exact problem, deleting lines:
> 
> https://github.com/m4xshen/autoclose.nvim/blob/ec7bf9013584e92e0a07b190c936b2c4563e961a/lua/autoclose.lua#L18-L19
> fixed this for me though, perhaps it's remapping <CR>?

Do you also use coc?

**Comment by ripytide** [comment]
> Do you also use coc?

I do not, I use the build-in nvim LSP with nvim-cmp etc..

**Comment by DonnieWest** [comment]
I can also confirm autoclose disables the enter key on my computer. Deleting those lines also fixes the problem for me

I also use the build-in LSP w/ nvim-cmp

**Comment by m4xshen** [comment]
@DonnieWest could you disable the nvim-cmp and then try whether the enter key works?

**Comment by DonnieWest** [comment]
That was my assumption too. Disabling nvim-cmp didn't fix it for me.

FWIW I narrowed it down to this plugin by disabling my plugins in a binary-search like fashion. It was only by disabling this plugin that I solved the problem

**Comment by m4xshen** [comment]
What's your config options for autoclose.nvim?

**Comment by DonnieWest** [comment]
I can replicate the issue by simply calling setup with no config supplied, or the entire default config passed in
