### ISSUE TITLE
Adding support for html/xml tags.

### ISSUE THREAD

**Issue by Matblanket** [m4xshen/autoclose.nvim#12]
Currently when writing html, '<' autocompletes with '>'. 

I was thinking of extending the plugin to autocomplete the end tag when completing the initial tag.
Eg. when typing `<body>`, the plugin automatically adds `</body>` in a new line.

**Comment by m4xshen** [comment]
This plugin is designed to be minimal, so I probably won't implement this feature in the future. There are already a [plugin](https://github.com/windwp/nvim-ts-autotag) that can auto pair html/xml tags. You can install it alongside autoclose.nvim.
