### ISSUE TITLE
completely disable specific keys: `'` and `"`

### ISSUE THREAD

**Issue by gilbh** [m4xshen/autoclose.nvim#13]
Great plugin, but I don't want it to work for `'` and `"` (actually, for any duplication of an identical key).

I tried the following:
```
  require("autoclose").setup({
    ["'"] = { escape = false, close = false, pair = "''"},
    ['"'] = { escape = false, close = false, pair = '""'},
  }) 
```

-- but they automated closing still happens.

How to completely disable specific keys?

Thanks!

**Comment by m4xshen** [comment]
You should put these in a "keys" table. Take a look at the example config.

**Comment by m4xshen** [comment]
Oh, I forgot to update some part of the example config. I will fix that soon.

**Comment by gilbh** [comment]
Indeed, that did the trick! Thanks!!
