### ISSUE TITLE
Escape does not work after auto-indent / multiline was triggered

### ISSUE THREAD

**Issue by mikehaertl** [m4xshen/autoclose.nvim#15]
When auto-indent is activated it seems escaping the current section does no longer work

* `nvim test.md`
* Go to insert mode
* Press `"`: you see `"|"` (`|` indicates cursor position)
* Press `<CR>`: you see
    ```
    "
   |
    "
    ```
* Press `abc` followed by `"`: you see
    ```
    "
   abc"|"
    "
    ```

I would have expected that the second `"` character triggers escape and I see this instead:
```
"
abc
"|
```

Or is there another way to escape the current section if you're editing a multiline text?

**Comment by m4xshen** [comment]
This plugin only provides escape function in the same line now. I recommend you to use `<C-o>j` to escape multi line text efficiently.

**Comment by mikehaertl** [comment]
Oh, that's nice. I didn't even know this shortcut and had to look it up. For those like me: `:h i_CTRL-O`.

So thanks for pointing me to that (and many more useful shortcuts in insert mode that I just learned about).
