### ISSUE TITLE
Auto-delete does not work with CTRL-W / CTRL-U

### ISSUE THREAD

**Issue by mikehaertl** [m4xshen/autoclose.nvim#16]
This is rather a feature request:

When using `CTRL-W` or `CTRL-U` in insert mode to delete an opening bracket it will not delete the closing bracket. Maybe this could be added?

**Comment by m4xshen** [comment]
This feature is added in cfa572b88d8eb30089d78444e19afbd85a51efab, but I only add the `CTRL-W` cause I think it is better for `CTRL-U` to remain it's original behavior.
