### ISSUE TITLE
Add an option to not add closing half of the pair when it's next to a none whitespace character

### ISSUE THREAD

**Issue by ryuheechul** [m4xshen/autoclose.nvim#17]
Autoclose.nvim is convinient when I freshly type things like below.
```
   cursor
     |
     V 
(word|)
```

However I actually edit more than write I often find myself doing very inefficient editing like following.
```
; move the cursor to a existing word
|word

; type (
(|)word

; delete ) - this is a multiple key strokes
(|word

; put ) at the end
(word)|
```

I came up with a simple idea. Perhaps not adding a closing half of the pair when the cursor is "touching" the word.
So it would be nice if this plugin can offer an option like that.

**Comment by m4xshen** [comment]
This options is added in 8ed364d39a7e09265f283d5ec0ce88e3a6806f41. Thanks for your feedback.

**Comment by ryuheechul** [comment]
Works perfectly, thank you!
