### ISSUE TITLE
Disable autoclose in certain situations

### ISSUE THREAD

**Issue by AlexXi19** [m4xshen/autoclose.nvim#25]
is it possible to only enable autoclose then it is at the end of line?

**Comment by m4xshen** [comment]
Why do you want to do this?

**Comment by AlexXi19** [comment]
Because end of line usually means that I'm typing something new. For autoclose completions not at the line, i find that it's more inaccurate than accurate. Is it possible to add something like this? If you don't like this option, I can also fork the repo and try to implemented this myself.
