### ISSUE TITLE
Option to double space

### ISSUE THREAD

**Issue by Notarin** [m4xshen/autoclose.nvim#26]
For the sake of demonstration, I will use `|` to represent the cursor
Currently, when I press `{` it will result in this: `{|}`, which is expected.
However, I like to add a space before and after the content within the brackets, like this:
```lua
use { 'm4xshen/autoclose.nvim' }
```
Currently, If I start with `{|}` and press space, it results in `{ |}`, which is not ideal, if im inside two braces and there is no content, and I press space, I'd like it to result in `{ | }`, which I feel flows best.
Thank you for your time.

**Comment by m4xshen** [comment]
You can now set `pair_spaces = true` inside `options` to enable this feature!

**Comment by Notarin** [comment]
@m4xshen apologies for the late response, but thank you!
