### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by hachy** [m4xshen/autoclose.nvim#28]
Just a question.
Are you using a code formatter? Or are you planning to use one?

**Comment by m4xshen** [comment]
No I'm not using code formatter. Why do you ask this?

**Comment by hachy** [comment]
Ok. Is it possible to add StyLua or something?
I think it is easy to contribute without worrying about the minor details of the code.

**Comment by m4xshen** [comment]
Sure, this idea sounds great. I'll consider adding this in the future.
