### ISSUE TITLE
Ignore specific keys for filetype

### ISSUE THREAD

**Issue by driesceuppens** [m4xshen/autoclose.nvim#30]
This plugin works great and I have been using it for some time. However even with the `disable_filetypes` option I notice it is only certain keys I want to disable. For instance in markdown files I want to disable `'` because it's part of normal grammer but `()` and `[]` are part of markdown and I want them to autoclose. Is there any current way to do this?

**Comment by driesceuppens** [comment]
Taking a look at the code it should be possible to check for a keys specific setting like
```
keys = {
    ["{"] = { escape = true, close = true, pair = "{}", disable_filetypes = { "markdown" } },
}
```
and then check in the `haldler(info, key)` check if for the `info.disable_filetypes` if it is equal to the filetype or something.

I could take a look to make this change myself if that's okay.

**Comment by m4xshen** [comment]
Sure, you can open a pr to make this change. This is a great feature that I didn't think of!
