### ISSUE TITLE
Make touch regex configurable

### ISSUE THREAD

**Issue by mikehaertl** [m4xshen/autoclose.nvim#33]
I'd like to supress autoclose not only for alphanum characters to the right of the cursor. This could be easily achieved if the `%w` regex here would be configurable:

https://github.com/m4xshen/autoclose.nvim/blob/a9ecd7ef80af7caada66e1215172722ec2d61d64/lua/autoclose.lua#L106-L107

**Comment by m4xshen** [comment]
Add `touch_regex` option in fb1530a. Thanks for the feedback!
