### ISSUE TITLE
Consider documenting a short comparison to nvim-autopairs

### ISSUE THREAD

**Issue by basilkohler** [m4xshen/autoclose.nvim#37]
I was setting up nvim and looking for a lua version for closing brackets.
I found your project and nvim-autopairs (which seems more popular due to star count).

It seems like you saw a need in writing a new plugin. You could consider adding some infos to the Rradme comparing the two plugins as well as the advantages of autoclose.nvim. This would have helped me to decide which one to use.

Thank you for your work.

**Comment by m4xshen** [comment]
Thanks for the feedback!
