### ISSUE TITLE
Make it possible to correct close the double string like /*

### ISSUE THREAD

**Issue by dmtrKovalenko** [m4xshen/autoclose.nvim#39]
I'd like to use you awesome plugin to autoclose the inline block comments in typescript/js. eg

```js
/* this is the comment */
```

But when I added the config 

```lua
          ["/*"] = {
            escape = true,
            close = true,
            pair = "/**/",
            enabled_filetypes = { "typescript", "typescriptreact", "javascript", "javascriptreact" }
          },
```

Auto pair works incorrectly because when it adds a pair cursor is moved to the last character `/**{here}/` instead of `/*{here}*/`

https://github.com/m4xshen/autoclose.nvim/assets/16926049/079f667c-c553-46e4-9d33-ccd4ad067e88

**Comment by m4xshen** [comment]
Same as #23. I'll fix this soon.
