### ISSUE TITLE
<BS> in signs that `[ [ ] " " " ' ' ' (() { { }` already have matched will delete both

### ISSUE THREAD

**Issue by NEX-S** [m4xshen/autoclose.nvim#4]
I find something weird,
in the cases that has been already matched like `[ [ ] " " " ' ' ' (() { { }`, we dont want autoclose.nvim to delete both signs for us
for example:
```c
|  <------- Cursor
#include "stdio.h"|"
```
as we can see, `"stdio.h"|"` have a pair that already matched ( `"stdio.h"|`), if we press `<BS>` at `|`, it will delete the both sign for us.
In this cases, we might not wish to delete both sign :D

**Comment by wookayin** [comment]
@NEX-S why did you close this issue?
