### ISSUE TITLE
autoclose inserts a closing bracket even when editing a string

### ISSUE THREAD

**Issue by ggoraa** [m4xshen/autoclose.nvim#44]
I have no idea if this is fixable, but it's a little annoying to remove the not-required bracket each time I edit a string and want to insert a bracket or something similar
Still, this is a good plugin, keep up the good work!

**Comment by telemachus** [comment]
@ggoraa You can always insert a single character (without triggering the plugin) if you enter `<C-v><character>`. For example, `<C-v>(`.

See [`:help i_CTRL-V`](https://neovim.io/doc/user/insert.html#i_CTRL-V).

**Comment by m4xshen** [comment]
@telemachus thanks for the detail explanation. The `<C-v>` trick is pretty brilliant!
