### ISSUE TITLE
Add an ability to jump "outside" on hotkey

### ISSUE THREAD

**Issue by savchenko** [m4xshen/autoclose.nvim#48]
Picture this:

```
foo = bar(baz['blah'](b*leh{'one'{'two', 'three'}}))
                       ^
                     cursor
```

Now imagine you can move cursor to each closing character via, for example, <kbd>Shift+Enter</kbd>. Sounds cool?

**Comment by m4xshen** [comment]
This can be done with [tabout.nvim](https://github.com/abecodes/tabout.nvim)!
