### ISSUE TITLE
How to delete the plugin ?

### ISSUE THREAD

**Issue by Watynecc** [m4xshen/autoclose.nvim#5]
Hello I wanted to know how to delete it... I did a :PackerClean but yet it's still here ?

**Comment by m4xshen** [comment]
Do you remove the line `use 'm4xshen/autoclose.nvim'` before `:PackerClean`?

**Comment by Watynecc** [comment]
Yes I did it, I will recheck just for sure

**Comment by m4xshen** [comment]
If that doesn't work. You can remove the plugin directly with `rm -r ~/.local/share/nvim/site/pack/packer/start/autoclose.nvim`.
