### ISSUE TITLE
Broken autoindent inside lua-heredoc

### ISSUE THREAD

**Issue by Serega124** [m4xshen/autoclose.nvim#59]
Hello.
Unlike regular lua files, autoindent inside lua-heredoc seem doesn't work as expected:

![test](https://github.com/user-attachments/assets/8553398c-7889-4a93-b5c5-d36c2967d13f)

**Comment by m4xshen** [comment]
Hi @Serega124 , seems that the issue can be reproduce with `autoclose.nvim` disabled.

For example (here `|` represents cursor):

```vim
lua << END
require('test').setup {|}
END
```

I press enter and it becomes:

```vim
lua << END
require('test').setup {
  }
END
```

Therefore this should be the issue of Neovim itself?

**Comment by Serega124** [comment]
Yes, seems you are right
