### ISSUE TITLE
Strange indentation upon newline (enter)

### ISSUE THREAD

**Issue by wookayin** [m4xshen/autoclose.nvim#9]
```
{|<Enter>}
```

becomes:

```
{ 
        |
    }
```

whereas expected behavior is:

```
{
    |
}
```

GIF:

![CleanShot 2022-12-25 at 18 55 06](https://user-images.githubusercontent.com/1009873/209484990-b46b4dff-48e9-49f2-afba-11744de4216b.gif)

**Comment by m4xshen** [comment]
Please set smartindent to off.

**Comment by wookayin** [comment]
Hmm, why smartindent has to be off?

With `nosmartindent`, the outcome after keystrokes `(` `<CR>` or `{` `<CR>` would be:

```
(
|
)
```

```
{
|
}
```

whereas
```
{
    |
}
```
is an expected behavior that I would like to have with some config options.

**Comment by m4xshen** [comment]
Did you try this in the programming file, such as .lua ? Because in the text file no indent is the default action.
